In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Membaca file CSV
df = pd.read_csv('Hospitals.csv')
# Menampilkan 5 baris pertama
print(df.head())
# Menampilkan info kolom dan tipe data
print(df.info())
# Menampilkan ringkasan statistik (untuk data numerik)
print(df.describe())

           X          Y  OBJECTID         ID  \
0 -94.945477  29.747620      8497   76777520
1 -82.881843  40.027143      8498  129043230
2 -84.168027  39.774242      8499  130045404
3 -80.632972  41.005169      8500  128844512
4 -84.199398  39.747740      8501  129845417

                                                NAME  \
0  HOUSTON METHODIST SAN JACINTO HOSPITAL ALEXAND...
1                              WOODS AT PARKSIDE,THE
2                         DAYTON CHILDREN'S HOSPITAL
3                  VIBRA HOSPITAL OF MAHONING VALLEY
4             HAVEN BEHAVIORAL SENIOR CARE OF DAYTON

                          ADDRESS      CITY STATE    ZIP           ZIP4  ...  \
0          1700 JAMES BOWIE DRIVE   BAYTOWN    TX  77520  NOT AVAILABLE  ...
1          349 OLDE RIDENOUR ROAD  COLUMBUS    OH  43230  NOT AVAILABLE  ...
2             ONE CHILDRENS PLAZA    DAYTON    OH  45404  NOT AVAILABLE  ...
3               8049 SOUTH AVENUE  BOARDMAN    OH  44512  NOT AVAILABLE  ...
4  ONE ELIZABETH PLACE,E3 SUITE A    DAYTON    OH  45417  NOT AVAILABLE  ...

                   VAL_DATE  \
0  2017-12-18T00:00:00.000Z
1  2018-04-26T00:00:00.000Z
2  2018-04-26T00:00:00.000Z
3  2018-04-26T00:00:00.000Z
4  2018-04-26T00:00:00.000Z

                                             WEBSITE       STATE_ID  \
0  http://www.houstonmethodist.org/locations/san-...  NOT AVAILABLE
1                 http://www.thewoodsatparkside.com/           1815
2  http://www.childrensdayton.org/cms/home/index....           1411
3             http://www.mahoningvalleyhospital.com/           1428
4                https://dayton.havenbehavioral.com/           1506

                                   ALT_NAME ST_FIPS        OWNER TTL_STAFF  \
0                             NOT AVAILABLE    48.0   NON-PROFIT    -999.0
1                             NOT AVAILABLE    39.0  PROPRIETARY    -999.0
2                             NOT AVAILABLE    39.0   NON-PROFIT    -999.0
3  MAHONING VALLEY HOSPITAL BOARDMAN CAMPUS    39.0  PROPRIETARY    -999.0
4                             NOT AVAILABLE    39.0  PROPRIETARY    -999.0

    BEDS              TRAUMA        HELIPAD
0  182.0       NOT AVAILABLE              Y
1   50.0       NOT AVAILABLE  NOT AVAILABLE
2  155.0  PEDIATRIC LEVEL II              Y
3   45.0       NOT AVAILABLE  NOT AVAILABLE
4   32.0       NOT AVAILABLE  NOT AVAILABLE

[5 rows x 34 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7570 entries, 0 to 7569
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   X           7570 non-null   float64
 1   Y           7570 non-null   float64
 2   OBJECTID    7570 non-null   int64
 3   ID          7570 non-null   int64
 4   NAME        7570 non-null   object
 5   ADDRESS     7570 non-null   object
 6   CITY        7570 non-null   object
 7   STATE       7570 non-null   object
 8   ZIP         7570 non-null   int64
 9   ZIP4        7570 non-null   object
 10  TELEPHONE   7570 non-null   object
 11  TYPE        7570 non-null   object
 12  STATUS      7570 non-null   object
 13  POPULATION  7570 non-null   int64
 14  COUNTY      7570 non-null   object
 15  COUNTYFIPS  7570 non-null   object
 16  COUNTRY     7570 non-null   object
 17  LATITUDE    7570 non-null   float64
 18  LONGITUDE   7570 non-null   float64
 19  NAICS_CODE  7570 non-null   int64
 20  NAICS_DESC  7570 non-null   object
 21  SOURCE      7570 non-null   object
 22  SOURCEDATE  7570 non-null   object
 23  VAL_METHOD  7570 non-null   object
 24  VAL_DATE    7570 non-null   object
 25  WEBSITE     7570 non-null   object
 26  STATE_ID    7570 non-null   object
 27  ALT_NAME    7569 non-null   object
 28  ST_FIPS     7569 non-null   float64
 29  OWNER       7569 non-null   object
 30  TTL_STAFF   7569 non-null   float64
 31  BEDS        7569 non-null   float64
 32  TRAUMA      7569 non-null   object
 33  HELIPAD     7569 non-null   object
dtypes: float64(7), int64(5), object(22)
memory usage: 2.0+ MB
None
                 X            Y      OBJECTID            ID           ZIP  \
count  7570.000000  7570.000000   7570.000000  7.570000e+03   7570.000000
mean    -92.387417    37.331745  11287.911889  2.520163e+07  53609.916645
std      15.995659     5.775099   2189.726558  3.899382e+07  27518.769850
min    -176.640263   -14.290242   7497.000000  4.000000e+00    605.000000
25%     -98.199507    33.463963   9392.250000  3.974885e+06  32028.000000
50%     -90.074141    37.976913  11288.000000  9.640840e+06  54966.000000
75%     -81.774617    41.322441  13183.750000  2.241059e+07  76781.000000
max     145.724472    71.292847  15081.000000  1.676842e+08  99929.000000

        POPULATION     LATITUDE    LONGITUDE     NAICS_CODE      ST_FIPS  \
count  7570.000000  7570.000000  7570.000000    7570.000000  7569.000000
mean     42.392999    37.331744   -92.387417  622140.951123    29.472189
std     370.336773     5.775099    15.995660      66.107596    16.304241
min    -999.000000   -14.290242  -176.640263  622110.000000     1.000000
25%      25.000000    33.463963   -98.199507  622110.000000    17.000000
50%      65.000000    37.976913   -90.074141  622110.000000    29.000000
75%     178.000000    41.322441   -81.774617  622110.000000    44.000000
max    1592.000000    71.292847   145.724472  622310.000000    78.000000

       TTL_STAFF         BEDS
count     7569.0  7569.000000
mean      -999.0    48.257233
std          0.0   362.645616
min       -999.0  -999.000000
25%       -999.0    25.000000
50%       -999.0    66.000000
75%       -999.0   178.000000
max       -999.0  1592.000000

In [14]:
sns.histplot(df['Number of Beds'], kde=True)
plt.title('Distribusi Jumlah Tempat Tidur')
plt.xlabel('Jumlah Tempat Tidur')
plt.ylabel('Frekuensi')
plt.show()

KeyError: 'Number of Beds'